# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'My' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for My
  pod 'RxSwift', '6.2.0'
  target 'MyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyUITests' do
    # Pods for testing
  end

end
